version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  web:
    image: nginx:1.18-alpine
    ports:
      - ${WEB_PORT:-8080}:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    platform: linux/x86_64
    build: ./infra/mysql
    ports:
      - ${DB_PORT:-33060}:3306
    volumes:
      - db-store:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PHP_MYADMIN_PORT:-8888}:80
    depends_on:
      - db

volumes:
  db-store:
